-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3nLj2eJvDikqFOaD
e+eq2z/IFzXH1YpR6iGITaDvr2OgCgYIKoZIzj0DAQehRANCAAQQW9CaPVyH6SZt
rxJrnEo93HwWKVileBnkwO/e//9R2SVUqvCO+Pglg3rpdM4lj6BARYiOtj4QiyCs
FTE6IfoJ
-----END PRIVATE KEY-----